# version
version: '3.8'
services:
  api: 
    build: 
      ./api
    container_name: 
      api_container
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
      - ./app/node_modules

  frontend:
    build:
      ./frontend
    container_name:
      frontend_container
    ports:
      - '3000:3000'
    stdin_open: true # start in interactive mode
    tty: true # start in interactive mode
    # volumes:
    #   - ./frontend:/app
    #   - ./app/node_modules

